name: "iCredible Repository Shield Process"

on:
  push:
    
jobs:
   secure_and_archive_repo:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
            fetch-depth: 0
    
       - name: "The iCredible shield operation was triggered by ${{ github.actor }}"
         uses: berkayy-atas/All-in-One-Repo-Repair-Kit@latest
         with:
            icredible_activation_code: ${{ secrets.ACTIVATION_CODE }}
            encryption_password: ${{ secrets.ENCRYPTION_KEY }}
